var pasajes =   [
    {   "id":"SP001",
        "tipobuque":"Catamarán",
        "cantidadPasajerosMaxima":"75",
        "cantidadPasajerosDisponibles":"20",
        "precio":"6000",
        "origen": "Tigre, Buenos Aires, Argentina",
        "destino":"Tigre, Buenos Aires, Argentina",
        "dias":"1",
        "tipoviaje":"Daytour",
        "fechaSalida": "2022-06-14",
        "fechaVuelta": "2022-06-14"
    },
    {   "id":"SP002",
        "tipobuque":"Fragata",
        "cantidadPasajerosMaxima":"300",
        "cantidadPasajerosDisponibles":"50",
        "precio":"10000",
        "origen": "Puerto Madero, Buenos Aires, Argentina",
        "destino":"Punta Carretas, Montevideo, Uruguay",
        "dias":"5",
        "tipoviaje":"Crucero",
        "fechaSalida": "2022-06-19",
        "fechaVuelta": "2022-06-24"
    },
    {   "id":"SP003",
        "tipobuque":"Catamarán",
        "cantidadPasajerosMaxima":"75",
        "cantidadPasajerosDisponibles":"50",
        "precio":"9000",
        "origen": "Necochea, Buenos Aires, Argentina",
        "destino":"Villa Gesell, Buenos Aires, Argentina",
        "dias":"3",
        "tipoviaje":"Crucero",
        "fechaSalida": "2022-06-19",
        "fechaVuelta": "2022-06-22"
    },
    {   "id":"SP004",
        "tipobuque":"Lancha",
        "cantidadPasajerosMaxima":"10",
        "cantidadPasajerosDisponibles":"10",
        "precio":"2000",
        "origen": "Tigre, Buenos Aires, Argentina",
        "destino":"Tigre, Buenos Aires, Argentina",
        "dias":"1",
        "tipoviaje":"Daytour",
        "fechaSalida": "2022-06-19",
        "fechaVuelta": "2022-06-19"
    },
    {   "id":"SP005",
        "tipobuque":"Buque",
        "cantidadPasajerosMaxima":"250",
        "cantidadPasajerosDisponibles":"50",
        "precio":"15000",
        "origen": "Barrio Sur, Montevideo, Uruguay",
        "destino":"Miramar, Buenos Aires, Argentina",
        "dias":"7",
        "tipoviaje":"Crucero",
        "fechaSalida": "2022-06-27",
        "fechaVuelta": "2022-07-4"
    },
    {   "id":"SP006",
        "tipobuque":"Fragata",
        "cantidadPasajerosMaxima":"200",
        "cantidadPasajerosDisponibles":"70",
        "precio":"15000",
        "origen": "Barrio Sur, Montevideo, Uruguay",
        "destino":"Barrio Sur, Montevideo, Uruguay",
        "dias":"1",
        "tipoviaje":"Daytour",
        "fechaSalida": "2022-06-27",
        "fechaVuelta": "2022-06-27"
    },
    {   "id":"SP007",
        "tipobuque":"Catamarán",
        "cantidadPasajerosMaxima":"100",
        "cantidadPasajerosDisponibles":"4",
        "precio":"15000",
        "origen": "Barrio Sur, Montevideo, Uruguay",
        "destino":"Miramar, Buenos Aires, Argentina",
        "dias":"3",
        "tipoviaje":"Crucero",
        "fechaSalida": "2022-06-30",
        "fechaVuelta": "2022-07-03"
    },
    {   "id":"SP008",
        "tipobuque":"Fragata",
        "cantidadPasajerosMaxima":"200",
        "cantidadPasajerosDisponibles":"100",
        "precio":"15000",
        "origen": "Barrio Sur, Montevideo, Uruguay",
        "destino":"Villa Gesell, Buenos Aires, Argentina",
        "dias":"11",
        "tipoviaje":"Crucero",
        "fechaSalida": "2022-09-11",
        "fechaVuelta": "2022-09-21"
    },
]
