var usuarios = [
    {   "nombre":"",
        "apellido":"",
        "domicilio":"",
        "dni":"",
        "mercadoPago":"",
        "CVU": "",
        "aliasMP":"",
        "cuentaBancaria":"",
        "CBU":"",
        "aliasCB": "",
        "tarjetadeCredito": "",
        "nombre": "",
        "numero": "",
        "vencimiento": "",
        "codigoSeguridad": ""
    },
    {   "nombre":"",
        "apellido":"",
        "domicilio":"",
        "dni":"",
        "mercadoPago":"",
        "CVU": "",
        "aliasMP":"",
        "cuentaBancaria":"",
        "CBU":"",
        "aliasCB": "",
        "tarjetadeCredito": "",
        "nombre": "",
        "numero": "",
        "vencimiento": "",
        "codigoSeguridad": ""
    },
    {   "nombre":"",
        "apellido":"",
        "domicilio":"",
        "dni":"",
        "mercadoPago":"",
        "CVU": "",
        "aliasMP":"",
        "cuentaBancaria":"",
        "CBU":"",
        "aliasCB": "",
        "tarjetadeCredito": "",
        "nombre": "",
        "numero": "",
        "vencimiento": "",
        "codigoSeguridad": ""
    }
]